version: 2

seeds:
  - name: region_codes
    description: A mapping of two letter region codes to country names
    columns:
      - name: region_name
        tests:
          - unique
          - not_null
      - name: alpha2
        tests:
          - unique
          - not_null
  - name: speaking_codes
    description: A mapping of two letter language codes to country names
    columns:
      - name: english_name
        tests:
          - unique
          - not_null
      - name: alpha2
        tests:
          - unique
          - not_null